### PR TITLE
Add Optipng optimizer

### PR DESCRIPTION
**Pull request by zergin**
- http://optipng.sourceforge.net/

### CODE REVIEW

**Comment by heynemann** [comment]
@guilhermef what do you think?

**Comment by guilhermef** [comment]
@zergin do you mind removing the version bump from the PR ?
We still have to think on a better way to import Configs inside Thumbor.

**Comment by zergin** [comment]
Sure. Done.

**Comment by guilhermef** [comment]
Thanks @zergin

**Pull request merged**
