### PR TITLE
Clean setup & makefile

### PR DESCRIPTION
**Pull request by zergin**
- remove copy/pasta Makefile entries
- allow clean installs (w/o test dependencies)
- declare optimizers package for pip installs

### CODE REVIEW

**Comment by heynemann** [comment]
@guilhermef seems like a great PR! :)

**Comment by guilhermef** [comment]
@zergin I just think that we should always install with the [tests] packages on make install.
Since we're dealing with someone that is installing for development.

**Comment by zergin** [comment]
Yes and no ;-) Initially I was installing from source in a docker container and I couldn't care less for tests (and all dependencies it required). I just wanted to see if the code would work/suit my purpose (and pip install was broken at the time). 

My point being - there are smallish environments that benefit from (almost) no dependencies. Always forcing dependencies won't make people write better code/more tests.

**Comment by guilhermef** [comment]
I just think it's better to follow a pattern, since Thumbor's setup does the same thing.
It's nice to have the same behavior when running make setup.

**Comment by zergin** [comment]
Ok - uniformity with thumbor makes sense and wins with my preference. I've altered Makefile even more to that end and also restored original "setup" label.

**Comment by guilhermef** [comment]
Thanks @zergin

**Pull request merged**
