### PR TITLE
Auto optimizer

### PR DESCRIPTION
**Pull request by okor**
This is it. This ... is the one. I think.

So this optimizer does two things:
  - automatically converts PNG's to JPEG's if they *really* don't have any alpha pixels in the image, otherwise leaves it encoded as PNG
  - optimizes every image (png and jpeg) with Imgmin (awesome, but slow)

Imgmin really is slow but I think most folks are behind caching layers and we can put a big "WARNING this thing is slow" disclaimer in the Wiki. Other than that, this plugin is pretty great. 

FYI: I think we (Vox Media) will continue to use Webp on Chrome and use `auto` everywhere else. The reason is the jpeg2000 encoder is a bit of a wildcat and sometimes has negative compression, which sucks. It's also kind of slept on and almost nobody is using it. Conversely, webp is awesome, fast and predictable. So for all non-Chrome we are just going to use auto. That also means one less format to support and one less file to cache. On the statistically insignificant number of images I've run through this optimizer, I've been getting very good results near Webp stats.

Anecdotally, I noticed that imgmin speed of compression could be plotted like a hockey stick, where X is time and Y is image resolution. For small files (< 1000x1000) it's not really noticeable (700ms locally, 4.7ghz 4core). For very large images it's kind of brutal (4-12 seconds). Especially for PNG's. Again, if you have the capacity and caching, it probably won't be a problem but you've been warned.

Once we have our new EC2 autoscaling staging Thumbor cluster setup completed, I'll give feedback as to the difference in load and whether our Systems/Ops teams like it. And same if we do roll it out in production.

### CODE REVIEW

**Comment by guilhermef** [comment]
@okor It looks amazing!!

**Comment by okor** [comment]
Oh, forgot to mention that if you are using auto webp, everything will still work. So if you used a pure server side implementation, just generate all your urls with the `/filter:format(auto)/` option. And when you are in Chrome, you will get Webp. Everything else will get png/jpeg.

**Comment by guilhermef** [comment]
thanks @okor

**Comment by okor** [comment]
Thank!

**Pull request merged**
