### PR TITLE
Add options to jpeg-recompress

### PR DESCRIPTION
**Pull request by estahn**

### CODE REVIEW

**Comment by guilhermef** [comment]
@estahn Can you add some tests ? 
You can find some test examples on /tests and /vows folders.

**Comment by estahn** [comment]
@guilhermef I can try, but never have done any python before.

**Comment by guilhermef** [comment]
You can copy the ones on the tests or vows folder,
and add the dependency to the requirements file.

**Comment by guilhermef** [comment]
@estahn You should at least test the command formation

**Pull request closed without merging**
