### PR TITLE
convert image to correct mode for formatting it to jpeg2000

### PR DESCRIPTION
**Pull request by bagipriyank**

### CODE REVIEW

**Comment by bagipriyank** [comment]
@guilhermef could you please have a look, and if you merge it, could you also please release it? thanks!

**Comment by bagipriyank** [comment]
any update on this?

**Comment by bagipriyank** [comment]
any update on this?

**Comment by bagipriyank** [comment]
can we please merge it and release a new version?

**Comment by bagipriyank** [comment]
@kkopachev can we please merge this pr and release a new version?

**Comment by guilhermef** [comment]
@bagipriyank I'll release a new version, thanks for the PR

**Comment by guilhermef** [comment]
I've released the new version: https://pypi.org/project/thumbor-plugins/0.2.4/
I tried to fix the current build, but the imgmin package install is broken on Ubuntu 16.04.

**Pull request merged**
