### PR TITLE
Mozjpeg optimizer

### PR DESCRIPTION
**Pull request by okor**
This PR would add a mozjpeg optimizer. Requires mozjpeg binary on host (cjpeg on cli). All tests pass. Used it on a local version of Thumbor, definitely works.

- install the plugins: `cd <thumbor path> && pip install -I https://github.com/okor/thumbor-plugins/archive/mozjpeg.zip`
- add 'thumbor_plugins.optimizers.mozjpeg' to the OPTIMIZERS array in the thumbor config
- optionally, tune `MOZJPEG_QUALITY=...` in config, otherwise defaults to 75

Now all jpegs will pass through the mozjpeg optimizer.

### CODE REVIEW

**Comment by okor** [comment]
Ugh, right. I'll work on the travis file

**Comment by okor** [comment]
Sorry for the ugliness in the travis.yml, it's getting a little crazy in there. I wonder if we should consider moving to a Docker'ized flow for Travis? I haven't done that before but it seems like it would be simpler to make changes to the env with Docker, since people could easily test it locally. Rather than be surprised that a build is failing because my dev env is different from Travis. Ideally, `make test` would rebuild a local Docker image and then run tests. That 

Not entirely relevant to this PR but in the grander scheme it is.

**Comment by masom** [comment]
@okor That would be great.

There has been a few attempts to add a Dockerfile to the project and it should be doable.

**Comment by okor** [comment]
@masom Ok cool. I think it's out of scope for this PR and really don't want to change two things at once but will create an issue and hack on it soon.

**Comment by guilhermef** [comment]
@okor that's a great idea, I saw a few Thumbor's Dockerfile https://hub.docker.com/r/elsdoerfer/thumbor/

**Comment by guilhermef** [comment]
Oh, and the PR looks good.

**Comment by okor** [comment]
@guilhermef Thanks! I'll add some docs.

**Comment by okor** [comment]
Ok, docs added here. Feel free to sanity check and change https://github.com/thumbor/thumbor-plugins/wiki/Mozjpeg

**Pull request merged**
