### PR TITLE
bump to 0.2.2

### PR DESCRIPTION
**Pull request by bagipriyank**

### CODE REVIEW

**Comment by bagipriyank** [comment]
@guilhermef

**Comment by bagipriyank** [comment]
@guilhermef

**Comment by bagipriyank** [comment]
any update on this?

**Comment by guilhermef** [comment]
Thanks @bagipriyank, sorry for taking too long to merge it.
I'll release a new version on Pypi now.

**Comment by bagipriyank** [comment]
thank you :D

**Pull request merged**
